-- Friend requests and the symmetric friendship they produce.
--
-- Following (`user_follows`) is one-directional and needs no consent; friendship
-- is mutual and gated on the other side accepting, so it needs a request record
-- with a lifecycle as well as an edge table.
CREATE TABLE IF NOT EXISTS friend_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    addressee_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message VARCHAR(200) NOT NULL DEFAULT '',
    -- 'pending' is the only live state; the rest are terminal and kept so the
    -- two sides can see what happened to a request they remember sending.
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMPTZ NULL,
    CONSTRAINT friend_requests_no_self CHECK (requester_user_id <> addressee_user_id),
    CONSTRAINT friend_requests_status_known
        CHECK (status IN ('pending', 'accepted', 'declined', 'cancelled'))
);

-- At most one open request per ordered pair. Partial, so the terminal history
-- can hold any number of earlier attempts.
CREATE UNIQUE INDEX IF NOT EXISTS idx_friend_requests_pending_pair
    ON friend_requests(requester_user_id, addressee_user_id)
    WHERE status = 'pending';

-- The two listings a client asks for: my inbox and my outbox, newest first.
CREATE INDEX IF NOT EXISTS idx_friend_requests_addressee_created
    ON friend_requests(addressee_user_id, status, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_friend_requests_requester_created
    ON friend_requests(requester_user_id, status, created_at DESC, id DESC);

-- One row per friendship, with the pair stored in ascending id order. Storing
-- the canonical order instead of both directions makes the relation symmetric by
-- construction: there is no way to represent a half-friendship, and no second
-- row to keep in step when one side is deleted.
CREATE TABLE IF NOT EXISTS friendships (
    low_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    high_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (low_user_id, high_user_id),
    CONSTRAINT friendships_canonical_order CHECK (low_user_id < high_user_id)
);

-- Listing my friends walks whichever column I am in, so both need an index.
CREATE INDEX IF NOT EXISTS idx_friendships_low_created
    ON friendships(low_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_friendships_high_created
    ON friendships(high_user_id, created_at DESC);
