-- Gifts: the spend side of the points economy.
--
-- Check-in only ever credits points, so until now `user_point_transactions`
-- held nothing but positive deltas. A gift is the first debit: sending one
-- writes a negative ledger row and a `gift_records` row that points back at it.
--
-- Points are burned, not transferred. Crediting the recipient would let two
-- accounts trade the same points back and forth at no cost, and would inflate
-- `user_point_balances.total_earned`, which is supposed to mean "earned".
CREATE TABLE IF NOT EXISTS gift_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stable machine key, so a client can special-case artwork or an animation
    -- without keying off a row id or a display name that admins may rename.
    gift_key VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(40) NOT NULL,
    description VARCHAR(200) NOT NULL DEFAULT '',
    -- Either a short glyph (an emoji is the default case) or an asset URL; the
    -- client decides by inspecting it, so no separate discriminator column.
    icon VARCHAR(300) NOT NULL DEFAULT '',
    price_points INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    -- Disabled gifts stay listable for history rendering but cannot be sent.
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT gift_catalog_key_format CHECK (gift_key ~ '^[a-z0-9_]{2,40}$'),
    CONSTRAINT gift_catalog_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT gift_catalog_price_range CHECK (price_points >= 0 AND price_points <= 1000000)
);

-- The room panel reads exactly this: enabled rows in display order.
CREATE INDEX IF NOT EXISTS idx_gift_catalog_enabled_sort
    ON gift_catalog(is_enabled, sort_order, id);

CREATE TABLE IF NOT EXISTS gift_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Nulled when the recipient deletes their account. The row survives because
    -- the sender's statement must still reconcile against the ledger.
    recipient_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    -- NULL for a gift sent from a profile instead of from a room.
    room_id BIGINT NULL REFERENCES rooms(id) ON DELETE SET NULL,
    -- RESTRICT, not CASCADE: a catalog entry that has been sent must be
    -- disabled rather than deleted, or history would lose its subject.
    gift_id BIGINT NOT NULL REFERENCES gift_catalog(id) ON DELETE RESTRICT,
    -- Snapshotted at send time. The catalog may be renamed or repriced later,
    -- and a record has to keep saying what was sent and what it cost.
    gift_key VARCHAR(40) NOT NULL,
    gift_name VARCHAR(40) NOT NULL,
    gift_icon VARCHAR(300) NOT NULL DEFAULT '',
    unit_price_points INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    total_points BIGINT NOT NULL,
    -- The debit this send paid through, so a statement row and a gift row can
    -- be shown as one event. Nulled only if the ledger row is ever pruned.
    transaction_id BIGINT NULL REFERENCES user_point_transactions(id) ON DELETE SET NULL,
    message VARCHAR(200) NOT NULL DEFAULT '',
    -- Caller-supplied idempotency key. A retried send (flaky network, double
    -- tap) must charge once; the partial unique index below enforces that while
    -- still allowing many rows with no key at all.
    request_id VARCHAR(64) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gift_records_quantity_range CHECK (quantity >= 1 AND quantity <= 99),
    CONSTRAINT gift_records_unit_price_non_negative CHECK (unit_price_points >= 0),
    CONSTRAINT gift_records_total_non_negative CHECK (total_points >= 0),
    CONSTRAINT gift_records_total_matches_unit CHECK (total_points = unit_price_points::BIGINT * quantity),
    -- Sending to yourself is a no-op that would only be used to fake activity.
    CONSTRAINT gift_records_no_self_gift CHECK (recipient_id IS NULL OR recipient_id <> sender_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_gift_records_sender_request
    ON gift_records(sender_id, request_id)
    WHERE request_id IS NOT NULL;

-- "What have I sent" and "what have I received", newest first.
CREATE INDEX IF NOT EXISTS idx_gift_records_sender_created
    ON gift_records(sender_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_gift_records_recipient_created
    ON gift_records(recipient_id, created_at DESC, id DESC)
    WHERE recipient_id IS NOT NULL;
-- The room's own gift feed.
CREATE INDEX IF NOT EXISTS idx_gift_records_room_created
    ON gift_records(room_id, created_at DESC, id DESC)
    WHERE room_id IS NOT NULL;

-- Seed a starter catalog so the panel is not empty before an admin visits.
-- Prices are deliberately spread across the check-in award (10/day by default):
-- the cheapest is one day's claim, the dearest is a month of them.
INSERT INTO gift_catalog (gift_key, name, description, icon, price_points, sort_order)
VALUES
    ('flower',    '鲜花',   '一朵小花，聊表心意',   '🌹', 10,  10),
    ('milk_tea',  '奶茶',   '请你喝一杯',           '🧋', 30,  20),
    ('popcorn',   '爆米花', '一起看片的标配',       '🍿', 50,  30),
    ('rocket',    '火箭',   '带你冲上云霄',         '🚀', 150, 40),
    ('crown',     '皇冠',   '今天你最大',           '👑', 300, 50)
ON CONFLICT (gift_key) DO NOTHING;
