-- 情侣空间: a two-account shared space.
--
-- The space is a relationship with a lifecycle, so it is a row rather than a
-- symmetric edge: an invite exists before the partner agrees, and an ended
-- space stays readable afterwards.
CREATE TABLE IF NOT EXISTS couple_spaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    partner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    title VARCHAR(100) NOT NULL DEFAULT '',
    invite_message VARCHAR(200) NOT NULL DEFAULT '',
    -- The date the couple counts from; the "在一起 N 天" counter reads it.
    -- Defaults to the bind date when the partner accepts without setting one.
    anniversary_date DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bound_at TIMESTAMPTZ NULL,
    ended_at TIMESTAMPTZ NULL,
    CONSTRAINT couple_spaces_no_self CHECK (initiator_user_id <> partner_user_id),
    CONSTRAINT couple_spaces_status_known
        CHECK (status IN ('pending', 'active', 'ended')),
    CONSTRAINT couple_spaces_active_is_bound
        CHECK (status <> 'active' OR bound_at IS NOT NULL),
    CONSTRAINT couple_spaces_ended_has_timestamp
        CHECK (status <> 'ended' OR ended_at IS NOT NULL)
);

-- One open invite per direction; the terminal history is unconstrained.
CREATE UNIQUE INDEX IF NOT EXISTS idx_couple_spaces_pending_pair
    ON couple_spaces(initiator_user_id, partner_user_id)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_couple_spaces_initiator
    ON couple_spaces(initiator_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_couple_spaces_partner
    ON couple_spaces(partner_user_id, status, created_at DESC);

-- Active membership, extracted so the database can enforce "at most one active
-- space per account". Partial unique indexes on `couple_spaces` could not: a
-- user appears in one column or the other, and nothing there stops them being
-- the initiator of one active space and the partner of another. Here the
-- account *is* the primary key, so a second active space cannot be inserted.
CREATE TABLE IF NOT EXISTS couple_space_members (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_couple_space_members_space
    ON couple_space_members(couple_space_id);

-- The couple's shared list. Distinct from `user_media_favorites`: either partner
-- can add to it, and both see it.
CREATE TABLE IF NOT EXISTS couple_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    added_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    room_id BIGINT NULL REFERENCES rooms(id) ON DELETE SET NULL,
    media_id BIGINT NULL,
    title VARCHAR(300) NOT NULL,
    cover_url VARCHAR(500) NOT NULL DEFAULT '',
    source_key VARCHAR(200) NOT NULL,
    note VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT couple_favorites_source_key_not_blank CHECK (length(btrim(source_key)) > 0),
    CONSTRAINT couple_favorites_space_source_unique UNIQUE (couple_space_id, source_key)
);

CREATE INDEX IF NOT EXISTS idx_couple_favorites_space_created
    ON couple_favorites(couple_space_id, created_at DESC, id DESC);
