-- Personal watch history and media favourites.
--
-- `room_playback_history` already records what a *room* played, keyed by room
-- and sequence. The "我的" surfaces need the opposite projection: what one
-- account watched, across rooms, newest first. Deriving that from the room
-- table would need a scan per room the user ever joined, so the per-user view
-- gets its own table.
--
-- Titles and covers are denormalised on purpose: an entry has to keep reading
-- correctly after the room, the playlist or the media row is gone, which is
-- exactly when a history list matters most.
CREATE TABLE IF NOT EXISTS user_watch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Nullable so a deleted room leaves the entry readable but unopenable.
    room_id BIGINT NULL REFERENCES rooms(id) ON DELETE SET NULL,
    -- No FK: `media` is keyed by (id, room_id) and an entry outlives its media.
    media_id BIGINT NULL,
    title VARCHAR(300) NOT NULL,
    cover_url VARCHAR(500) NOT NULL DEFAULT '',
    position_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
    duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
    -- Stable identity of what was watched, supplied by the caller. Re-watching
    -- the same thing updates the row in place instead of growing the list.
    source_key VARCHAR(200) NOT NULL,
    watched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_watch_history_position_non_negative CHECK (position_seconds >= 0),
    CONSTRAINT user_watch_history_duration_non_negative CHECK (duration_seconds >= 0),
    CONSTRAINT user_watch_history_source_key_not_blank CHECK (length(btrim(source_key)) > 0),
    CONSTRAINT user_watch_history_user_source_unique UNIQUE (user_id, source_key)
);

-- The list itself: one account, newest first.
CREATE INDEX IF NOT EXISTS idx_user_watch_history_user_watched
    ON user_watch_history(user_id, watched_at DESC, id DESC);

-- Media the account starred. Room favourites already live in `user_favorite_rooms`;
-- this is the other half of the "我的收藏" page.
CREATE TABLE IF NOT EXISTS user_media_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_id BIGINT NULL REFERENCES rooms(id) ON DELETE SET NULL,
    media_id BIGINT NULL,
    title VARCHAR(300) NOT NULL,
    cover_url VARCHAR(500) NOT NULL DEFAULT '',
    source_key VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_media_favorites_source_key_not_blank CHECK (length(btrim(source_key)) > 0),
    CONSTRAINT user_media_favorites_user_source_unique UNIQUE (user_id, source_key)
);

CREATE INDEX IF NOT EXISTS idx_user_media_favorites_user_created
    ON user_media_favorites(user_id, created_at DESC, id DESC);
