-- Subscription sources an administrator publishes to every account.
--
-- The client already distinguishes a server source from a device-local one and
-- refuses to edit the former; until now nothing produced any, so every account
-- had to import the same endpoints by hand on every device. These rows are that
-- missing half.
CREATE TABLE IF NOT EXISTS vod_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    -- How to read the endpoint. The client has adapters for each; an unknown
    -- value would leave a row nothing can parse, so the set is closed here.
    format VARCHAR(16) NOT NULL,
    endpoint TEXT NOT NULL,
    -- Sent with every catalog request. Some sources gate on User-Agent or
    -- Referer; a browser build cannot set those and drops them.
    headers JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Disabled rows stay editable and stop being served to clients, which is
    -- how a source is retired without losing what it was.
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    -- No FK cascade to a room or a user's content: a source outlives whoever
    -- added it, so a deleted administrator leaves the row and drops the name.
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vod_sources_format_known
        CHECK (format IN ('maccms_json', 'maccms_xml', 'm3u')),
    CONSTRAINT vod_sources_name_present CHECK (length(btrim(name)) > 0),
    CONSTRAINT vod_sources_endpoint_present CHECK (length(btrim(endpoint)) > 0),
    -- Two rows for one endpoint are always a mistake, and catching it here
    -- means the admin form does not have to.
    CONSTRAINT vod_sources_endpoint_unique UNIQUE (endpoint)
);

-- The client listing is "the enabled sources, in the order an admin set".
CREATE INDEX IF NOT EXISTS idx_vod_sources_enabled_order
    ON vod_sources (sort_order, id)
    WHERE enabled;
