-- Daily check-in and the points it awards.
--
-- Three tables, one per concern: the ledger (`user_point_transactions`) is the
-- append-only truth, the balance (`user_point_balances`) is its cached fold, and
-- `user_check_ins` is the once-per-day claim record. The claim table exists
-- separately from the ledger because "has this account already checked in
-- today?" must be answerable by primary key, not by scanning a ledger window.
CREATE TABLE IF NOT EXISTS user_point_balances (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    balance BIGINT NOT NULL DEFAULT 0,
    -- Lifetime earnings, kept because spending must not erase what was earned.
    total_earned BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_point_balances_balance_non_negative CHECK (balance >= 0),
    CONSTRAINT user_point_balances_total_earned_non_negative CHECK (total_earned >= 0)
);

CREATE TABLE IF NOT EXISTS user_point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Signed: awards are positive, future spending negative.
    delta BIGINT NOT NULL,
    -- Balance after this row was applied, so a statement renders without a fold.
    balance_after BIGINT NOT NULL,
    reason VARCHAR(40) NOT NULL,
    description VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_point_transactions_delta_not_zero CHECK (delta <> 0),
    CONSTRAINT user_point_transactions_balance_after_non_negative CHECK (balance_after >= 0)
);

CREATE INDEX IF NOT EXISTS idx_user_point_transactions_user_created
    ON user_point_transactions(user_id, created_at DESC, id DESC);

-- One row per account per day. The primary key is the idempotency guarantee:
-- two concurrent check-in requests cannot both award points.
CREATE TABLE IF NOT EXISTS user_check_ins (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    check_in_date DATE NOT NULL,
    points_awarded INTEGER NOT NULL,
    -- Consecutive days ending on this one, computed at claim time.
    streak INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, check_in_date),
    CONSTRAINT user_check_ins_points_non_negative CHECK (points_awarded >= 0),
    CONSTRAINT user_check_ins_streak_positive CHECK (streak >= 1)
);

CREATE INDEX IF NOT EXISTS idx_user_check_ins_user_date
    ON user_check_ins(user_id, check_in_date DESC);

-- Admin-owned award rules. A single row (id = 1) rather than a settings section:
-- the runtime settings machinery needs coordinated edits across a struct, an
-- update mask, change detection and validation, which is a lot of surface for
-- five numbers that only this feature reads.
CREATE TABLE IF NOT EXISTS check_in_config (
    id SMALLINT PRIMARY KEY DEFAULT 1,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    -- 'fixed' awards `fixed_points`; 'random' draws from the inclusive range.
    award_mode VARCHAR(16) NOT NULL DEFAULT 'fixed',
    fixed_points INTEGER NOT NULL DEFAULT 10,
    random_min_points INTEGER NOT NULL DEFAULT 1,
    random_max_points INTEGER NOT NULL DEFAULT 20,
    -- Which clock decides "today". Defaults to UTC+8: with a UTC boundary the
    -- day would roll over at 08:00 for the users this deployment serves.
    day_boundary_offset_minutes INTEGER NOT NULL DEFAULT 480,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT check_in_config_single_row CHECK (id = 1),
    CONSTRAINT check_in_config_award_mode_known CHECK (award_mode IN ('fixed', 'random')),
    CONSTRAINT check_in_config_fixed_points_range CHECK (fixed_points >= 0 AND fixed_points <= 100000),
    CONSTRAINT check_in_config_random_min_range CHECK (random_min_points >= 0 AND random_min_points <= 100000),
    CONSTRAINT check_in_config_random_max_range CHECK (random_max_points >= 0 AND random_max_points <= 100000),
    CONSTRAINT check_in_config_random_range_ordered CHECK (random_min_points <= random_max_points),
    CONSTRAINT check_in_config_offset_range CHECK (day_boundary_offset_minutes BETWEEN -720 AND 840)
);

-- Seed the defaults so a fresh install can check in before an admin visits.
INSERT INTO check_in_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
