-- 爱的小窝: what a bound pair keeps together beyond the two lists they already had.
--
-- Everything hangs off `couple_space_id` and cascades with the space. There is no
-- per-row owner check anywhere: a couple space has exactly two members and both
-- may read and write all of it, so authorisation is "are you in this space",
-- resolved once in the service.

-- 时光轴 ---------------------------------------------------------------------
-- One dated entry. `happened_on` is the day being remembered, which is not the
-- day it was written: a trip is usually written up afterwards, and the timeline
-- must order by the former.
CREATE TABLE couple_memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    author_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    happened_on DATE NOT NULL,
    title VARCHAR(120) NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    location VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT couple_memories_has_something CHECK (
        length(btrim(title)) > 0 OR length(btrim(content)) > 0
    )
);

CREATE INDEX idx_couple_memories_space_day
    ON couple_memories (couple_space_id, happened_on DESC, id DESC);

-- 相册 -----------------------------------------------------------------------
CREATE TABLE couple_albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    name VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT couple_albums_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT couple_albums_name_unique UNIQUE (couple_space_id, name)
);

-- 媒体 -----------------------------------------------------------------------
-- One table for both sources. The home screen shows "recent shared media"
-- across albums and timeline entries alike, and two tables would make that a
-- union that has to be re-sorted and re-paged in the service.
--
-- `album_id` and `memory_id` are both nullable and both may be set: a photo
-- attached to a memory can also be filed in an album. A row with neither is
-- loose media, which is what an upload straight into 相册 with no album is.
--
-- Blob identity is (storage_backend, object_key), matching chat attachments;
-- the row keeps enough shape (mime, size, dimensions) to lay out a grid without
-- fetching the object. The blob itself is kept alive by a `file_references`
-- row with reference_kind = 'couple_media'.
CREATE TABLE couple_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    album_id BIGINT REFERENCES couple_albums(id) ON DELETE SET NULL,
    memory_id BIGINT REFERENCES couple_memories(id) ON DELETE CASCADE,
    uploader_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    -- 1 photo, 2 video. Kept numeric to match the wire enum.
    media_kind SMALLINT NOT NULL,
    storage_backend TEXT NOT NULL,
    object_key TEXT NOT NULL,
    mime_type TEXT NOT NULL DEFAULT '',
    size_bytes BIGINT,
    width INTEGER,
    height INTEGER,
    -- When the photo was taken, when that is known; the grid groups by it.
    taken_on DATE,
    caption VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT couple_media_kind_known CHECK (media_kind IN (1, 2)),
    CONSTRAINT couple_media_object_key_not_blank CHECK (length(btrim(object_key)) > 0),
    CONSTRAINT couple_media_width_positive CHECK (width IS NULL OR width > 0),
    CONSTRAINT couple_media_height_positive CHECK (height IS NULL OR height > 0),
    CONSTRAINT couple_media_size_positive CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT couple_media_object_unique UNIQUE (couple_space_id, storage_backend, object_key)
);

CREATE INDEX idx_couple_media_space_recent
    ON couple_media (couple_space_id, created_at DESC, id DESC);
CREATE INDEX idx_couple_media_album
    ON couple_media (album_id, created_at DESC, id DESC) WHERE album_id IS NOT NULL;
CREATE INDEX idx_couple_media_memory
    ON couple_media (memory_id, created_at ASC, id ASC) WHERE memory_id IS NOT NULL;

-- 首页封面: one of the pair's own photos, so it is a media row rather than a URL.
ALTER TABLE couple_spaces
    ADD COLUMN cover_media_id BIGINT REFERENCES couple_media(id) ON DELETE SET NULL;

-- 纪念日 ---------------------------------------------------------------------
-- Separate from `couple_spaces.anniversary_date`, which is the one date the
-- day-counter runs from. These are the many others: birthdays, first trip,
-- whatever the pair wants a countdown to.
CREATE TABLE couple_anniversaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(80) NOT NULL,
    happens_on DATE NOT NULL,
    -- A birthday repeats; "the day we moved in" does not.
    repeat_yearly BOOLEAN NOT NULL DEFAULT TRUE,
    note VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT couple_anniversaries_title_not_blank CHECK (length(btrim(title)) > 0)
);

CREATE INDEX idx_couple_anniversaries_space
    ON couple_anniversaries (couple_space_id, happens_on, id);

-- 清单 -----------------------------------------------------------------------
CREATE TABLE couple_todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(120) NOT NULL,
    note VARCHAR(300) NOT NULL DEFAULT '',
    category VARCHAR(40) NOT NULL DEFAULT '',
    -- 0 normal, 1 high. Room to grow without a migration.
    priority SMALLINT NOT NULL DEFAULT 0,
    plan_date DATE,
    -- Who ticked it, and when. Both null while it is outstanding.
    done_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    done_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT couple_todos_title_not_blank CHECK (length(btrim(title)) > 0),
    CONSTRAINT couple_todos_priority_known CHECK (priority BETWEEN 0 AND 2),
    -- Ticked means both are set, outstanding means neither is.
    CONSTRAINT couple_todos_done_consistent CHECK (
        (done_by_user_id IS NULL) = (done_at IS NULL)
    )
);

CREATE INDEX idx_couple_todos_space_open
    ON couple_todos (couple_space_id, done_at NULLS FIRST, plan_date NULLS LAST, id);

-- 宠物小屋 -------------------------------------------------------------------
-- One pet per space. Hunger and mood are stored as the value at `settled_at`
-- rather than as a live number: they decay with time, and a stored "current"
-- value would need a background job to stay honest. The reader applies the
-- decay, so a pet left alone for a week is hungry the moment it is opened.
CREATE TABLE couple_pets (
    couple_space_id BIGINT PRIMARY KEY REFERENCES couple_spaces(id) ON DELETE CASCADE,
    name VARCHAR(40) NOT NULL DEFAULT '',
    -- 1 cat, 2 dog, 3 fox, 4 rabbit. Numeric to match the wire enum.
    species SMALLINT NOT NULL DEFAULT 1,
    skin SMALLINT NOT NULL DEFAULT 0,
    accessory SMALLINT NOT NULL DEFAULT 0,
    stage SMALLINT NOT NULL DEFAULT 1,
    experience INTEGER NOT NULL DEFAULT 0,
    hunger SMALLINT NOT NULL DEFAULT 60,
    mood SMALLINT NOT NULL DEFAULT 60,
    settled_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT couple_pets_species_known CHECK (species BETWEEN 1 AND 4),
    CONSTRAINT couple_pets_stage_known CHECK (stage BETWEEN 1 AND 4),
    CONSTRAINT couple_pets_experience_positive CHECK (experience >= 0),
    CONSTRAINT couple_pets_hunger_range CHECK (hunger BETWEEN 0 AND 100),
    CONSTRAINT couple_pets_mood_range CHECK (mood BETWEEN 0 AND 100)
);

-- 续火花: one row per member per day they interacted with the pet. The streak is
-- derived from these rather than stored as a counter, because a counter cannot
-- answer "which days did we miss" and drifts the first time a write is lost.
CREATE TABLE couple_pet_checkins (
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    on_date DATE NOT NULL,
    interactions INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (couple_space_id, user_id, on_date),
    CONSTRAINT couple_pet_checkins_interactions_positive CHECK (interactions > 0)
);

CREATE INDEX idx_couple_pet_checkins_space_day
    ON couple_pet_checkins (couple_space_id, on_date DESC);

-- 心动 AI --------------------------------------------------------------------
-- Generated pieces are kept, not just shown: the reference's whole point is
-- that a love letter survives a page change. `prompt` keeps what was asked so a
-- piece can be regenerated or explained later.
CREATE TABLE couple_ai_works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_space_id BIGINT NOT NULL REFERENCES couple_spaces(id) ON DELETE CASCADE,
    author_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    -- 1 date plan, 2 diary, 3 love letter.
    kind SMALLINT NOT NULL,
    title VARCHAR(120) NOT NULL DEFAULT '',
    prompt JSONB NOT NULL DEFAULT '{}'::jsonb,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT couple_ai_works_kind_known CHECK (kind BETWEEN 1 AND 3),
    CONSTRAINT couple_ai_works_prompt_is_object CHECK (jsonb_typeof(prompt) = 'object'),
    CONSTRAINT couple_ai_works_content_not_blank CHECK (length(btrim(content)) > 0)
);

CREATE INDEX idx_couple_ai_works_space_recent
    ON couple_ai_works (couple_space_id, created_at DESC, id DESC);
