-- Direct and group conversations for the "消息" tab.
--
-- Room chat already exists, but it is scoped to a room and dies with it. These
-- conversations belong to the accounts in them: a direct thread between two
-- friends and a group a user created both outlive any room.
CREATE TABLE IF NOT EXISTS social_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(16) NOT NULL,
    -- Groups carry a name; direct threads render as the other participant.
    title VARCHAR(100) NOT NULL DEFAULT '',
    owner_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    -- 'low:high' user ids for a direct thread. Unique, so opening a DM twice
    -- lands in the same conversation instead of forking the history.
    direct_key VARCHAR(64) NULL,
    -- Cache of the newest message, kept so the conversation list can sort without
    -- an aggregate over every message. No FK: it is a pointer for ordering, and
    -- readers join to `social_messages` for the body so a removed message simply
    -- reads as empty.
    last_message_id BIGINT NULL,
    last_message_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT social_conversations_kind_known CHECK (kind IN ('direct', 'group')),
    CONSTRAINT social_conversations_direct_key_shape CHECK (
        (kind = 'direct' AND direct_key IS NOT NULL)
        OR (kind = 'group' AND direct_key IS NULL)
    ),
    CONSTRAINT social_conversations_group_has_title CHECK (
        kind <> 'group' OR length(btrim(title)) > 0
    ),
    CONSTRAINT social_conversations_direct_key_unique UNIQUE (direct_key)
);

CREATE INDEX IF NOT EXISTS idx_social_conversations_last_message
    ON social_conversations(last_message_at DESC NULLS LAST, id DESC);

CREATE TABLE IF NOT EXISTS social_conversation_members (
    conversation_id BIGINT NOT NULL REFERENCES social_conversations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL DEFAULT 'member',
    -- Read cursor: unread is "messages in this conversation newer than this id".
    last_read_message_id BIGINT NULL,
    muted BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (conversation_id, user_id),
    CONSTRAINT social_conversation_members_role_known
        CHECK (role IN ('owner', 'admin', 'member'))
);

-- "My conversations", the only listing the client asks for by user.
CREATE INDEX IF NOT EXISTS idx_social_conversation_members_user
    ON social_conversation_members(user_id, conversation_id);

CREATE TABLE IF NOT EXISTS social_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES social_conversations(id) ON DELETE CASCADE,
    -- NULL for the system lines that record joins, leaves and renames, and for a
    -- message whose author has since been deleted.
    sender_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    kind VARCHAR(16) NOT NULL DEFAULT 'text',
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Soft delete: a removed message still has to hold its place, because the
    -- read cursors of every other member are ids in this sequence.
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT social_messages_kind_known CHECK (kind IN ('text', 'system')),
    CONSTRAINT social_messages_body_length CHECK (length(body) <= 4000),
    CONSTRAINT social_messages_text_has_sender CHECK (kind <> 'text' OR sender_user_id IS NOT NULL)
);

-- Paging a thread backwards from the newest message, and the unread count.
CREATE INDEX IF NOT EXISTS idx_social_messages_conversation_id
    ON social_messages(conversation_id, id DESC);
