//! 爱的小窝: the nest a bound pair keeps — timeline, albums, media,
//! anniversaries, the shared list, the pet and the saved AI pieces.
//!
//! Generated by tool/gen_nest_http.py from a route table. Thirty handlers that
//! differ only in verb, message and rate-limit class: written out by hand, the
//! one transposed name that still compiles would route a call to the wrong
//! thing, and nothing would catch it.
//!
//! Every request names its `spaceId`; membership is resolved from it in the
//! service, so a stale client cannot write into a space it was unbound from.

use axum::{
    extract::State,
    routing::{get, post},
    Json, Router,
};

use super::{middleware::RequestMetadata, validation::ProtoQuery, AppResult, AppState};
use synctv_api_common::impls::EndpointRateLimitCategory;
use synctv_proto::client::{
    AddCoupleMediaRequest, AddCoupleMediaResponse, AdoptCouplePetRequest, AdoptCouplePetResponse,
    CreateCoupleAlbumRequest, CreateCoupleAlbumResponse, CreateCoupleAnniversaryRequest,
    CreateCoupleAnniversaryResponse, CreateCoupleMemoryRequest, CreateCoupleMemoryResponse,
    CreateCoupleTodoRequest, CreateCoupleTodoResponse, DeleteCoupleAiWorkRequest,
    DeleteCoupleAiWorkResponse, DeleteCoupleAlbumRequest, DeleteCoupleAlbumResponse,
    DeleteCoupleAnniversaryRequest, DeleteCoupleAnniversaryResponse, DeleteCoupleMediaRequest,
    DeleteCoupleMediaResponse, DeleteCoupleMemoryRequest, DeleteCoupleMemoryResponse,
    DeleteCoupleTodoRequest, DeleteCoupleTodoResponse, GetCoupleNestHomeRequest,
    GetCoupleNestHomeResponse, GetCouplePetHistoryRequest, GetCouplePetHistoryResponse,
    GetCouplePetRequest, GetCouplePetResponse, InteractWithCouplePetRequest,
    InteractWithCouplePetResponse, ListCoupleAiWorksRequest, ListCoupleAiWorksResponse,
    ListCoupleAlbumsRequest, ListCoupleAlbumsResponse, ListCoupleAnniversariesRequest,
    ListCoupleAnniversariesResponse, ListCoupleMediaRequest, ListCoupleMediaResponse,
    ListCoupleMemoriesRequest, ListCoupleMemoriesResponse, ListCoupleTodosRequest,
    ListCoupleTodosResponse, MoveCoupleMediaRequest, MoveCoupleMediaResponse,
    RenameCoupleAlbumRequest, RenameCoupleAlbumResponse, SaveCoupleAiWorkRequest,
    SaveCoupleAiWorkResponse, SetCoupleSpaceCoverRequest, SetCoupleSpaceCoverResponse,
    UpdateCoupleAnniversaryRequest, UpdateCoupleAnniversaryResponse, UpdateCoupleMemoryRequest,
    UpdateCoupleMemoryResponse, UpdateCouplePetRequest, UpdateCouplePetResponse,
    UpdateCoupleTodoRequest, UpdateCoupleTodoResponse,
};

pub(crate) fn routes() -> Router<AppState> {
    Router::new()
        .route("/api/user/couple/nest/home", get(get_couple_nest_home))
        .route(
            "/api/user/couple/nest/memories",
            get(list_couple_memories)
                .post(create_couple_memory)
                .patch(update_couple_memory)
                .delete(delete_couple_memory),
        )
        .route(
            "/api/user/couple/nest/albums",
            get(list_couple_albums)
                .post(create_couple_album)
                .patch(rename_couple_album)
                .delete(delete_couple_album),
        )
        .route(
            "/api/user/couple/nest/media",
            get(list_couple_media)
                .post(add_couple_media)
                .patch(move_couple_media)
                .delete(delete_couple_media),
        )
        .route("/api/user/couple/nest/cover", post(set_couple_space_cover))
        .route(
            "/api/user/couple/nest/anniversaries",
            get(list_couple_anniversaries)
                .post(create_couple_anniversary)
                .patch(update_couple_anniversary)
                .delete(delete_couple_anniversary),
        )
        .route(
            "/api/user/couple/nest/todos",
            get(list_couple_todos)
                .post(create_couple_todo)
                .patch(update_couple_todo)
                .delete(delete_couple_todo),
        )
        .route(
            "/api/user/couple/nest/pet",
            get(get_couple_pet)
                .post(adopt_couple_pet)
                .patch(update_couple_pet),
        )
        .route(
            "/api/user/couple/nest/pet/interact",
            post(interact_with_couple_pet),
        )
        .route(
            "/api/user/couple/nest/pet/history",
            get(get_couple_pet_history),
        )
        .route(
            "/api/user/couple/nest/ai-works",
            get(list_couple_ai_works)
                .post(save_couple_ai_work)
                .delete(delete_couple_ai_work),
        )
}

/// Media bytes, kept out of the table above: they need a body limit the JSON
/// routes must not have.
pub(crate) fn media_object_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/api/user/couple/nest/media-objects",
            post(upload_couple_media_object),
        )
        .route(
            "/api/user/couple/nest/media-objects/{mediaId}",
            get(get_couple_media_object),
        )
        // A couple photo, not a film: enough for a phone camera original and
        // a short clip, and small enough that a stray upload cannot exhaust
        // the box.
        .layer(axum::extract::DefaultBodyLimit::max(64 * 1024 * 1024))
}

/// Everything the nest home screen shows, in one read.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/home",
        tag = "Couple Nest",
        params(GetCoupleNestHomeRequest),
        responses((status = 200, description = "Everything the nest home screen shows, in one read", body = GetCoupleNestHomeResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn get_couple_nest_home(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<GetCoupleNestHomeRequest>,
) -> AppResult<Json<GetCoupleNestHomeResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move { client_api.get_couple_nest_home(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// 时光轴 entries, newest remembered day first.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/memories",
        tag = "Couple Nest",
        params(ListCoupleMemoriesRequest),
        responses((status = 200, description = "时光轴 entries, newest remembered day first", body = ListCoupleMemoriesResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn list_couple_memories(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<ListCoupleMemoriesRequest>,
) -> AppResult<Json<ListCoupleMemoriesResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move { client_api.list_couple_memories(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Writes a dated entry.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/memories",
        tag = "Couple Nest",
        request_body = CreateCoupleMemoryRequest,
        responses((status = 200, description = "Writes a dated entry", body = CreateCoupleMemoryResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn create_couple_memory(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<CreateCoupleMemoryRequest>,
) -> AppResult<Json<CreateCoupleMemoryResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.create_couple_memory(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Edits an entry; omitted fields keep their value.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        patch,
        path = "/api/user/couple/nest/memories",
        tag = "Couple Nest",
        request_body = UpdateCoupleMemoryRequest,
        responses((status = 200, description = "Edits an entry; omitted fields keep their value", body = UpdateCoupleMemoryResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn update_couple_memory(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<UpdateCoupleMemoryRequest>,
) -> AppResult<Json<UpdateCoupleMemoryResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.update_couple_memory(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Removes an entry and the media attached to it.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        delete,
        path = "/api/user/couple/nest/memories",
        tag = "Couple Nest",
        params(DeleteCoupleMemoryRequest),
        responses((status = 200, description = "Removes an entry and the media attached to it", body = DeleteCoupleMemoryResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn delete_couple_memory(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<DeleteCoupleMemoryRequest>,
) -> AppResult<Json<DeleteCoupleMemoryResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.delete_couple_memory(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Albums with their size and cover.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/albums",
        tag = "Couple Nest",
        params(ListCoupleAlbumsRequest),
        responses((status = 200, description = "Albums with their size and cover", body = ListCoupleAlbumsResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn list_couple_albums(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<ListCoupleAlbumsRequest>,
) -> AppResult<Json<ListCoupleAlbumsResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move { client_api.list_couple_albums(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Creates an album.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/albums",
        tag = "Couple Nest",
        request_body = CreateCoupleAlbumRequest,
        responses((status = 200, description = "Creates an album", body = CreateCoupleAlbumResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn create_couple_album(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<CreateCoupleAlbumRequest>,
) -> AppResult<Json<CreateCoupleAlbumResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.create_couple_album(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Renames an album.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        patch,
        path = "/api/user/couple/nest/albums",
        tag = "Couple Nest",
        request_body = RenameCoupleAlbumRequest,
        responses((status = 200, description = "Renames an album", body = RenameCoupleAlbumResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn rename_couple_album(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<RenameCoupleAlbumRequest>,
) -> AppResult<Json<RenameCoupleAlbumResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.rename_couple_album(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Removes the album; its photos survive as unfiled.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        delete,
        path = "/api/user/couple/nest/albums",
        tag = "Couple Nest",
        params(DeleteCoupleAlbumRequest),
        responses((status = 200, description = "Removes the album; its photos survive as unfiled", body = DeleteCoupleAlbumResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn delete_couple_album(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<DeleteCoupleAlbumRequest>,
) -> AppResult<Json<DeleteCoupleAlbumResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.delete_couple_album(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Photos and videos, filtered by album, memory or neither.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/media",
        tag = "Couple Nest",
        params(ListCoupleMediaRequest),
        responses((status = 200, description = "Photos and videos, filtered by album, memory or neither", body = ListCoupleMediaResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn list_couple_media(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<ListCoupleMediaRequest>,
) -> AppResult<Json<ListCoupleMediaResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move { client_api.list_couple_media(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Files an already-uploaded object into the nest.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/media",
        tag = "Couple Nest",
        request_body = AddCoupleMediaRequest,
        responses((status = 200, description = "Files an already-uploaded object into the nest", body = AddCoupleMediaResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn add_couple_media(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<AddCoupleMediaRequest>,
) -> AppResult<Json<AddCoupleMediaResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.add_couple_media(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Moves media between albums, or unfiles it.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        patch,
        path = "/api/user/couple/nest/media",
        tag = "Couple Nest",
        request_body = MoveCoupleMediaRequest,
        responses((status = 200, description = "Moves media between albums, or unfiles it", body = MoveCoupleMediaResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn move_couple_media(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<MoveCoupleMediaRequest>,
) -> AppResult<Json<MoveCoupleMediaResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.move_couple_media(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Removes one photo or video.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        delete,
        path = "/api/user/couple/nest/media",
        tag = "Couple Nest",
        params(DeleteCoupleMediaRequest),
        responses((status = 200, description = "Removes one photo or video", body = DeleteCoupleMediaResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn delete_couple_media(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<DeleteCoupleMediaRequest>,
) -> AppResult<Json<DeleteCoupleMediaResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.delete_couple_media(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Picks the home cover, or clears it.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/cover",
        tag = "Couple Nest",
        request_body = SetCoupleSpaceCoverRequest,
        responses((status = 200, description = "Picks the home cover, or clears it", body = SetCoupleSpaceCoverResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn set_couple_space_cover(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<SetCoupleSpaceCoverRequest>,
) -> AppResult<Json<SetCoupleSpaceCoverResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move {
                client_api
                    .set_couple_space_cover(&auth.user_id(), req)
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// 纪念日, soonest upcoming first.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/anniversaries",
        tag = "Couple Nest",
        params(ListCoupleAnniversariesRequest),
        responses((status = 200, description = "纪念日, soonest upcoming first", body = ListCoupleAnniversariesResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn list_couple_anniversaries(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<ListCoupleAnniversariesRequest>,
) -> AppResult<Json<ListCoupleAnniversariesResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move {
                client_api
                    .list_couple_anniversaries(&auth.user_id(), req)
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Adds a date to count down to.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/anniversaries",
        tag = "Couple Nest",
        request_body = CreateCoupleAnniversaryRequest,
        responses((status = 200, description = "Adds a date to count down to", body = CreateCoupleAnniversaryResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn create_couple_anniversary(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<CreateCoupleAnniversaryRequest>,
) -> AppResult<Json<CreateCoupleAnniversaryResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move {
                client_api
                    .create_couple_anniversary(&auth.user_id(), req)
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Edits a date.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        patch,
        path = "/api/user/couple/nest/anniversaries",
        tag = "Couple Nest",
        request_body = UpdateCoupleAnniversaryRequest,
        responses((status = 200, description = "Edits a date", body = UpdateCoupleAnniversaryResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn update_couple_anniversary(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<UpdateCoupleAnniversaryRequest>,
) -> AppResult<Json<UpdateCoupleAnniversaryResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move {
                client_api
                    .update_couple_anniversary(&auth.user_id(), req)
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Removes a date.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        delete,
        path = "/api/user/couple/nest/anniversaries",
        tag = "Couple Nest",
        params(DeleteCoupleAnniversaryRequest),
        responses((status = 200, description = "Removes a date", body = DeleteCoupleAnniversaryResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn delete_couple_anniversary(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<DeleteCoupleAnniversaryRequest>,
) -> AppResult<Json<DeleteCoupleAnniversaryResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move {
                client_api
                    .delete_couple_anniversary(&auth.user_id(), req)
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// 清单, outstanding first.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/todos",
        tag = "Couple Nest",
        params(ListCoupleTodosRequest),
        responses((status = 200, description = "清单, outstanding first", body = ListCoupleTodosResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn list_couple_todos(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<ListCoupleTodosRequest>,
) -> AppResult<Json<ListCoupleTodosResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move { client_api.list_couple_todos(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Adds something to do together.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/todos",
        tag = "Couple Nest",
        request_body = CreateCoupleTodoRequest,
        responses((status = 200, description = "Adds something to do together", body = CreateCoupleTodoResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn create_couple_todo(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<CreateCoupleTodoRequest>,
) -> AppResult<Json<CreateCoupleTodoResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.create_couple_todo(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Edits an item, or ticks it in the caller's name.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        patch,
        path = "/api/user/couple/nest/todos",
        tag = "Couple Nest",
        request_body = UpdateCoupleTodoRequest,
        responses((status = 200, description = "Edits an item, or ticks it in the caller's name", body = UpdateCoupleTodoResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn update_couple_todo(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<UpdateCoupleTodoRequest>,
) -> AppResult<Json<UpdateCoupleTodoResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.update_couple_todo(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Removes an item.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        delete,
        path = "/api/user/couple/nest/todos",
        tag = "Couple Nest",
        params(DeleteCoupleTodoRequest),
        responses((status = 200, description = "Removes an item", body = DeleteCoupleTodoResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn delete_couple_todo(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<DeleteCoupleTodoRequest>,
) -> AppResult<Json<DeleteCoupleTodoResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.delete_couple_todo(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// The pet, with hunger and mood decayed to now.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/pet",
        tag = "Couple Nest",
        params(GetCouplePetRequest),
        responses((status = 200, description = "The pet, with hunger and mood decayed to now", body = GetCouplePetResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn get_couple_pet(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<GetCouplePetRequest>,
) -> AppResult<Json<GetCouplePetResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move { client_api.get_couple_pet(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Adopts the space's pet.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/pet",
        tag = "Couple Nest",
        request_body = AdoptCouplePetRequest,
        responses((status = 200, description = "Adopts the space's pet", body = AdoptCouplePetResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn adopt_couple_pet(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<AdoptCouplePetRequest>,
) -> AppResult<Json<AdoptCouplePetResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.adopt_couple_pet(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Renames or re-dresses the pet.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        patch,
        path = "/api/user/couple/nest/pet",
        tag = "Couple Nest",
        request_body = UpdateCouplePetRequest,
        responses((status = 200, description = "Renames or re-dresses the pet", body = UpdateCouplePetResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn update_couple_pet(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<UpdateCouplePetRequest>,
) -> AppResult<Json<UpdateCouplePetResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.update_couple_pet(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Feeds, plays with or strokes the pet.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/pet/interact",
        tag = "Couple Nest",
        request_body = InteractWithCouplePetRequest,
        responses((status = 200, description = "Feeds, plays with or strokes the pet", body = InteractWithCouplePetResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn interact_with_couple_pet(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<InteractWithCouplePetRequest>,
) -> AppResult<Json<InteractWithCouplePetResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move {
                client_api
                    .interact_with_couple_pet(&auth.user_id(), req)
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// 续火花 history, one entry per day.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/pet/history",
        tag = "Couple Nest",
        params(GetCouplePetHistoryRequest),
        responses((status = 200, description = "续火花 history, one entry per day", body = GetCouplePetHistoryResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn get_couple_pet_history(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<GetCouplePetHistoryRequest>,
) -> AppResult<Json<GetCouplePetHistoryResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move {
                client_api
                    .get_couple_pet_history(&auth.user_id(), req)
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Saved 心动 AI pieces.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        get,
        path = "/api/user/couple/nest/ai-works",
        tag = "Couple Nest",
        params(ListCoupleAiWorksRequest),
        responses((status = 200, description = "Saved 心动 AI pieces", body = ListCoupleAiWorksResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn list_couple_ai_works(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<ListCoupleAiWorksRequest>,
) -> AppResult<Json<ListCoupleAiWorksResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move { client_api.list_couple_ai_works(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Keeps a generated piece.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        post,
        path = "/api/user/couple/nest/ai-works",
        tag = "Couple Nest",
        request_body = SaveCoupleAiWorkRequest,
        responses((status = 200, description = "Keeps a generated piece", body = SaveCoupleAiWorkResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn save_couple_ai_work(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    Json(req): Json<SaveCoupleAiWorkRequest>,
) -> AppResult<Json<SaveCoupleAiWorkResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.save_couple_ai_work(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

/// Removes a saved piece.
#[cfg_attr(
    feature = "openapi",
    utoipa::path(
        delete,
        path = "/api/user/couple/nest/ai-works",
        tag = "Couple Nest",
        params(DeleteCoupleAiWorkRequest),
        responses((status = 200, description = "Removes a saved piece", body = DeleteCoupleAiWorkResponse)),
        security(("bearer_auth" = []))
    )
)]
pub async fn delete_couple_ai_work(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    ProtoQuery(req): ProtoQuery<DeleteCoupleAiWorkRequest>,
) -> AppResult<Json<DeleteCoupleAiWorkResponse>> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let response = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move { client_api.delete_couple_ai_work(&auth.user_id(), req).await },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(response))
}

// ---------------------------------------------------------- media objects ---
// Photo and video bytes. Both directions are HTTP-only, like every other object
// route in the app: a stream does not belong in a proto message.

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct CoupleMediaObjectPath {
    media_id: String,
}

#[derive(Debug, Default, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct CoupleMediaUploadQuery {
    space_id: String,
    #[serde(default)]
    kind: i32,
    #[serde(default)]
    album_id: Option<String>,
    #[serde(default)]
    memory_id: Option<String>,
    #[serde(default)]
    caption: Option<String>,
    #[serde(default)]
    taken_on: Option<String>,
    #[serde(default)]
    width: Option<i32>,
    #[serde(default)]
    height: Option<i32>,
}

/// Stores one photo or video and files it into the nest.
pub async fn upload_couple_media_object(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    axum::extract::Query(query): axum::extract::Query<CoupleMediaUploadQuery>,
    headers: axum::http::HeaderMap,
    body: axum::body::Bytes,
) -> AppResult<Json<synctv_proto::client::AddCoupleMediaResponse>> {
    let mime = headers
        .get(axum::http::header::CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .unwrap_or("application/octet-stream")
        .to_string();
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let media = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Write,
            |auth| async move {
                client_api
                    .upload_couple_media_object(
                        &auth.user_id(),
                        &query.space_id,
                        query.kind,
                        &mime,
                        body.to_vec(),
                        query.album_id.as_deref(),
                        query.memory_id.as_deref(),
                        query.caption.as_deref().unwrap_or_default(),
                        query.taken_on.as_deref().unwrap_or_default(),
                        query.width.unwrap_or_default(),
                        query.height.unwrap_or_default(),
                    )
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    Ok(Json(synctv_proto::client::AddCoupleMediaResponse {
        media: Some(media),
    }))
}

/// Streams one item back to a member of its space.
///
/// No token in the URL: the caller is authenticated as themselves and checked
/// against the space, so a link to a couple photo is worthless to anyone else
/// even if it leaks into a log or a referrer.
pub async fn get_couple_media_object(
    request_meta: RequestMetadata,
    State(state): State<AppState>,
    axum::extract::Path(path): axum::extract::Path<CoupleMediaObjectPath>,
) -> AppResult<axum::response::Response> {
    let executor = state.shared_api_runtime.client_api.clone();
    let client_api = state.shared_api_runtime.client_api.clone();
    let download = executor
        .execute_user_endpoint(
            &request_meta.0,
            EndpointRateLimitCategory::Read,
            |auth| async move {
                client_api
                    .couple_media_object_download(&auth.user_id(), &path.media_id)
                    .await
            },
        )
        .await
        .map_err(super::error::map_api_error)?;
    // Immutable: a media row never points at a different object once written.
    super::file_object_download_response(download, Some("private, max-age=31536000, immutable"))
}
